### ISSUE TITLE
Base controller and category reconciliation 

### ISSUE THREAD

**Issue by evgheni7** [web-seven/provider-magento#4]
### What problem are you facing?
After we created category schema is good time to try to do base provider controller, which will use Magento provider config for establishing client for connecting Magento rest api

### How could Crossplane help solve your problem?
- make provider config for Magento connecting credentials 
- make controller which will take provider config from category provider config ref field and will make connection client
- make reconciliation of category for create/update/delete categories.

**Comment by ca7alindev** [comment]
@evghen1 for provider config, credentials should be a magento token or username and password from magento?

**Comment by evgheni7** [comment]
@ca7alindev token
