### ISSUE TITLE
Cache Magento client

### ISSUE THREAD

**Issue by evgheni7** [web-seven/provider-magento#8]
### What problem are you facing?
Everytime provider requests magento client it creates new instance of RESTful client, what is not best on multiple invocations

### How could Crossplane help solve your problem?
Cache in memory magento client after first creation and return it next time from cache.

**Comment by evgheni7** [comment]
@ca7alindev PR was not assigned to this issues, shall we close it already?

**Comment by ca7alindev** [comment]
@evghen1 it should be closed by recently merged PR #9

**Comment by evgheni7** [comment]
@ca7alindev it was not closed because PR was not attached to issue, please close issue.
